### ISSUE TITLE
switch to nix 1.12 for all builders

### ISSUE THREAD

**Issue by Mic92** [NixOS/ofborg#10]
This is what hydra is using.
It also provides nicer logs.

**Comment by grahamc** [comment]
The aarch64 builders run Nix 1.12, and I think the mac does as well. I'll swap my Linux builder over soon to 1.12 and then check with the AWS account to see what they do.

**Comment by Mic92** [comment]
I think the switch was done.

**Comment by grahamc** [comment]
Ah! I think at least most builders are indeed running 1.12.

Thanks for following up!

Graham

**Comment by 7c6f434c** [comment]
Hm. I might have missed the transition and I do not remember what my builder runs… Maybe add a section in README (recommended Nix version: ≥2.0-pre, `nixUnstable` in `nixpkgs-unstable` channel)?
