### ISSUE TITLE
Possible optimization: Scheduled builds?

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/ofborg#127]
Hi,

I'm not that familiar with ofborg, so I don't know whether such a thing is already in place or planned. I'll submit this anyways, feel free to close this issue at any given time.

What I would like to propose are "Scheduled builds".

### Idea

ofborg does not immediately build the PR, but schedules the build to a later time. It collects a number of "scheduled builds" and if a limit is hit (either time limit or number of scheduled builds) it does a "automerge" and builds all requested changes.

(Automerge: It simulates a merge to the target branch and fast-forwards the target branch to that point on success).

### Usecase / where I come from

I maintain a set of rather small packages. When I update them I often only have to update the version number and the hash. Building _each_ of these packages immediately seems to be wasted energy from my POV. And I really don't care whether this small PR hits master ASAP or after 1/12/24 hours.

So from my point of view, waiting 24 hours until my "version bump for tool xyz" hits master is absolutely no problem - and it often is not! By collecting "scheduled PRs" and building them all at once, we save energy for more involved PRs.

In the best-case scenario we get 1 (one) build for 20 PRs. I would say that, because only version-bump PRs would be in scope for "scheduled builds", that's a rather common case as maintainers tend to build version-bump PRs on their own machine.

### On failure

If a "scheduled PR" fails to evaluate, one or more of the proposed PRs fail. That's the moment when ofborg has to do a reordering and merge all succeeding PRs (and merge them) to find the failing one - still less computing power required compared to "build them all".

---

I took this idea from how `bors` does it in the Rust community (to my best knowledge).

**Comment by Mic92** [comment]
Is your idea of `scheduled builds` not the same thing that `hydra` already implements?

**Comment by matthiasbeyer** [comment]
I'm not sure; as far as I understand it does hydra build the code _after_ it was merged? What I am proposing would still build the code _before_ it is merged - to ensure that master always builds.

**Comment by 7c6f434c** [comment]
Well, ogborg isn't yet even close to the amount of build power necessary to make sure `master` always builds…

**Comment by grahamc** [comment]
I appreciate the idea, but I don't think OfBorg will move to this model any time soon. A good bit of my interest is around speeding up the process of merging, not intentionally slowing it down. I do like the parallels with Bors, though. I think this model would require a very different build technique compared to OfBorg though, and isn't in the future plans.

Thank you, though!
