### ISSUE TITLE
Test command only works on aarch64

### ISSUE THREAD

**Issue by dotlambda** [NixOS/ofborg#128]
Tests seem to only be run on aarch64, see e.g. https://github.com/NixOS/nixpkgs/pull/36674#issuecomment-373911436.
Is this intended?

**Comment by dotlambda** [comment]
Also happened here:
- https://github.com/NixOS/nixpkgs/pull/37159#issuecomment-373913946
- https://github.com/NixOS/nixpkgs/pull/37103#issuecomment-373368930

**Comment by grahamc** [comment]
Thanks for the report, it turns out tests can't be run on Nix1 anymore and one of the builders was running Nix1. I've disabled that builder until it can be upgraded to Nix2.
