### ISSUE TITLE
nix.ci doesn't do much

### ISSUE THREAD

**Issue by wmertens** [NixOS/ofborg#137]
most of the links don't work… I found the graph at https://channels.nix.gsc.io/graph.html though.

**Comment by grahamc** [comment]
Hmm.. what links?

**Comment by wmertens** [comment]
https://nix.ci/alerts
https://nix.ci/graph
https://nix.ci/flags
https://nix.ci/config
https://nix.ci/rules
https://nix.ci/targets
https://nix.ci/
:)

**Comment by grahamc** [comment]
Oh right. That is because I'm only proxying that single page. I'd love to delete the header somehow, but I've not had the time.

**Comment by wmertens** [comment]
so it's not supposed to have all those pages? What about the graph?

**Comment by wmertens** [comment]
Is there any way I can assist with this? Where is the code for it? It is supposed to be a dashboard right?

**Comment by grahamc** [comment]
It does much more now! Thank you! Code is at https://github.com/ofborg/infrastructure
