### ISSUE TITLE
Build unfree packages

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/ofborg#194]
I understand the complexities of *distributing* software with an unfree license but any chance ofborg can start building those anyway?

**Comment by 7c6f434c** [comment]
>I understand the complexities of *distributing* software with an unfree license but any chance ofborg can start building those anyway?

Well, there are hopes to eventually have enough cross-replicated builds
on ofBorg to have something to push to Cachix.

**Comment by turion** [comment]
Any further plans to do this?

**Comment by rhendric** [comment]
This idea was rejected in #644; can someone close the issue?
