### ISSUE TITLE
Failure to run tests due to possibly older nix

### ISSUE THREAD

**Issue by samueldr** [NixOS/ofborg#195]
I am reporting the issue found in a PR I made:

https://github.com/NixOS/nixpkgs/pull/43237#issuecomment-403644290

> Indeed, it's reporting an assertion failure in closure-info.nix:11, which upon inspection is this:
> 
> ```nix
> assert builtins.langVersion >= 5;
> ```
> 
> So I'd guess the ofborg builder needs a Nix update or something? :)

<cite>— @dtzWill</cite>

I have not verified the assumptions, but am reporting the issue to ensure it will not get lost through time, and to provide an actionable item.

**Comment by LnL7** [comment]
Hmm, I thought all of the builders where running 2.0 now.

**Comment by xeji** [comment]
The builder showing this error is called `rbvermaa-spot`

**Comment by grahamc** [comment]
I've pinged Rob about this.

**Comment by Artturin** [comment]
Has never reappeared
