### ISSUE TITLE
[Feature requests] nixos tests

### ISSUE THREAD

**Issue by Mic92** [NixOS/ofborg#2]
if there are no tests for a given package, I have to build the package myself anyway to test functionality.
A green nixos test is more actionable.

**Comment by grahamc** [comment]
Is this asking for a thing like `@grahamcofborg test <testname>`? or something else?

**Comment by Mic92** [comment]
When I call `@grahamcofborg test ferm`,
borg could do the following:

```console
$ nix-build ./nixos/release.nix -A tests.ferm
```

A time limit would be recommend, because some broken tests tend to loop infinite.

**Comment by grahamc** [comment]
Don't the tests already have a maximum run time of 15min? or some timeout like that?

**Comment by Mic92** [comment]
I am not aware of a time limit.

**Comment by domenkozar** [comment]
`--option build-timeout 12345`

**Comment by grahamc** [comment]
`--option build-timout 12345` :)

**Comment by grahamc** [comment]
https://github.com/grahamc/ofborg#test-added-2017-11-24
