### ISSUE TITLE
Use the "checks" tab

### ISSUE THREAD

**Issue by vcunat** [NixOS/ofborg#231]
Borg's comments might now be movable to the new "checks" tab, separating the noise from actual discussion: https://help.github.com/articles/about-status-checks/#checks

_I haven't really looked into this possibility, so there might be some deal-breaker..._

**Comment by tilpner** [comment]
[It does now](https://discourse.nixos.org/t/ofborg-now-uses-checks/1558), this can probably be closed

**Comment by infinisil** [comment]
Well tbh, these checks are really fudgey in a way. I think I'd prefer having a single comment over them.

Reasons:
- They don't keep a history, you don't see how the build previously failed and now succeeds
- I'm never sure if these checks are up to date or are being updated
- I don't get a notification when the builds are done
- You need to click an additional time to see the checks, it's not open by default
- You don't see the build result immediately, you need to click the "Details" button (which then takes you to another page), which is already hidden behind the above mentioned button to see all checks. And just seeing green/gray isn't really enough most of the time.

I didn't like the previous state of 3+ comments on every single commend either, I think the best solution is just a single comment, and marking old comments as irrelevant (I think github allows for that now).

**Comment by vcunat** [comment]
> I'm never sure if these checks are up to date or are being updated

The commit hash is shown for each check.  On the whole I think it's really hard to please everyone.

**Comment by 7c6f434c** [comment]
I would say that not having notifications is inconvenient. I wonder if a single summary comment that gets posted no more often than once in three hours, hides the previous one, and contains everything that has changed would be a low enough noise level for people who prefer checks…

**Comment by vcunat** [comment]
I assume it might be a good compromise.  BTW, in GitLab each user can control their notifications from checks ("pipelines"), e.g. you may opt out of positive results.  If GitHub added some such options...

**Comment by grahamc** [comment]
I think it is safe to assume ofborg won't be getting any "single comment" behavior, and I'm quite sure a single comment will not behave suitably.

@vcunat is right, it is hard to please.

> I'm never sure if these checks are up to date or are being updated

We can create "Pending" states for the checks when they begin.

We could also revert checks and go back to comments.
