### ISSUE TITLE
OfBorg does not build tests

### ISSUE THREAD

**Issue by markuskowa** [NixOS/ofborg#273]
I noticed that OfBorg does not run test anymore with the error message:
`access to path '/nix/store/41dzsyb0a8lagqklasc5xb5nphqb8f8p-gleber-bastion' is forbidden in restricted mode` (https://github.com/NixOS/nixpkgs/pull/50862#issuecomment-440467333).
Is this intentional or am I overlooking something?

**Comment by grahamc** [comment]
It seems some change in nixpkgs has broken this and I haven’t been able to investigate.

**Comment by Mic92** [comment]
@GrahamcOfBorg build nixosTests.slurm is the workaround atm

**Comment by Mic92** [comment]
related pull request: https://github.com/NixOS/nixpkgs/pull/50342
