### ISSUE TITLE
Failed evaluation

### ISSUE THREAD

**Issue by jtojnar** [NixOS/ofborg#3]
Evaluation fails on https://github.com/NixOS/nixpkgs/pull/31683 for unknown reason, quoting @grahamc:

> ```
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   string(57) "Estimating rebuild amount by counting changed Hydra jobs."
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   [1]=>
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   string(155) "error: while evaluating anonymous function at /tmp/nix-rebuild-amount-YfwaDe6R:13:12, called from /tmp/nix-rebuild-amount-ZGmw0xJG/lib/attrsets.nix:199:52:"
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   [2]=>
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   string(111) "while evaluating the attribute ‘x86_64-darwin’ at /tmp/nix-rebuild-amount-ZGmw0xJG/lib/attrsets.nix:185:41:"
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   [3]=>
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   string(178) "while evaluating anonymous function at /tmp/nix-rebuild-amount-ZGmw0xJG/pkgs/top-level/release-lib.nix:66:6, called from /tmp/nix-rebuild-amount-ZGmw0xJG/lib/attrsets.nix:282:43:"
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   [4]=>
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   string(180) "while evaluating ‘hydraJob’ at /tmp/nix-rebuild-amount-ZGmw0xJG/lib/customisation.nix:157:14, called from /tmp/nix-rebuild-amount-ZGmw0xJG/pkgs/top-level/release-lib.nix:66:14:"
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   [5]=>
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   string(110) "while evaluating the attribute ‘drvPath’ at /tmp/nix-rebuild-amount-ZGmw0xJG/lib/customisation.nix:174:13:"
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   [6]=>
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   string(110) "while evaluating the attribute ‘drvPath’ at /tmp/nix-rebuild-amount-ZGmw0xJG/lib/customisation.nix:145:40:"
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   [7]=>
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   string(166) "while evaluating the attribute ‘cc’ of the derivation ‘clang-wrapper-3.4.2’ at /tmp/nix-rebuild-amount-ZGmw0xJG/pkgs/stdenv/generic/make-derivation.nix:98:11:"
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   [8]=>
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   string(167) "while evaluating the attribute ‘postInstall’ of the derivation ‘clang-3.4.2’ at /tmp/nix-rebuild-amount-ZGmw0xJG/pkgs/stdenv/generic/make-derivation.nix:98:11:"
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   [9]=>
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   string(165) "while evaluating the attribute ‘cmakeFlags’ of the derivation ‘llvm-3.4.2’ at /tmp/nix-rebuild-amount-ZGmw0xJG/pkgs/stdenv/generic/make-derivation.nix:98:11:"
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   [10]=>
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   string(135) "while evaluating the derivation attribute ‘name’ at /tmp/nix-rebuild-amount-ZGmw0xJG/pkgs/stdenv/generic/make-derivation.nix:98:11:"
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   [11]=>
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   string(119) "attribute ‘version’ missing, at /tmp/nix-rebuild-amount-ZGmw0xJG/pkgs/development/libraries/libbfd/default.nix:6:26"
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   [12]=>
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   string(155) "error: while evaluating anonymous function at /tmp/nix-rebuild-amount-MyLlifBZ:13:12, called from /tmp/nix-rebuild-amount-EXW3wJHS/lib/attrsets.nix:199:52:"
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   [13]=>
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   string(111) "while evaluating the attribute ‘x86_64-darwin’ at /tmp/nix-rebuild-amount-EXW3wJHS/lib/attrsets.nix:185:41:"
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   [14]=>
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   string(178) "while evaluating anonymous function at /tmp/nix-rebuild-amount-EXW3wJHS/pkgs/top-level/release-lib.nix:66:6, called from /tmp/nix-rebuild-amount-EXW3wJHS/lib/attrsets.nix:282:43:"
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   [15]=>
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   string(180) "while evaluating ‘hydraJob’ at /tmp/nix-rebuild-amount-EXW3wJHS/lib/customisation.nix:157:14, called from /tmp/nix-rebuild-amount-EXW3wJHS/pkgs/top-level/release-lib.nix:66:14:"
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   [16]=>
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   string(110) "while evaluating the attribute ‘drvPath’ at /tmp/nix-rebuild-amount-EXW3wJHS/lib/customisation.nix:174:13:"
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   [17]=>
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   string(110) "while evaluating the attribute ‘drvPath’ at /tmp/nix-rebuild-amount-EXW3wJHS/lib/customisation.nix:145:40:"
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   [18]=>
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   string(166) "while evaluating the attribute ‘cc’ of the derivation ‘clang-wrapper-3.4.2’ at /tmp/nix-rebuild-amount-EXW3wJHS/pkgs/stdenv/generic/make-derivation.nix:98:11:"
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   [19]=>
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   string(167) "while evaluating the attribute ‘postInstall’ of the derivation ‘clang-3.4.2’ at /tmp/nix-rebuild-amount-EXW3wJHS/pkgs/stdenv/generic/make-derivation.nix:98:11:"
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   [20]=>
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   string(165) "while evaluating the attribute ‘cmakeFlags’ of the derivation ‘llvm-3.4.2’ at /tmp/nix-rebuild-amount-EXW3wJHS/pkgs/stdenv/generic/make-derivation.nix:98:11:"
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   [21]=>
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   string(135) "while evaluating the derivation attribute ‘name’ at /tmp/nix-rebuild-amount-EXW3wJHS/pkgs/stdenv/generic/make-derivation.nix:98:11:"
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   [22]=>
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]:   string(119) "attribute ‘version’ missing, at /tmp/nix-rebuild-amount-EXW3wJHS/pkgs/development/libraries/libbfd/default.nix:6:26"
> Nov 15 14:30:17 zoidberg grahamcofborg-mass-rebuilder-start[29678]: }
> ```
> 
> I'll have to look in to why the eval check thinks this is OK, but the estimator thinks it isn't. Also, I need to fix the estimator to exit non-zero on eval errors :)

**Comment by grahamc** [comment]
Fixed, thank you!
