### ISSUE TITLE
buildRustPackage derivations fail ofBorg's sandboxed Darwin build due to cert error

### ISSUE THREAD

**Issue by lilyball** [NixOS/ofborg#332]
It looks like when we ask ofBorg to build a nixpkgs PR that uses `buildRustPackage`, the sandboxed Darwin build fails with a SSL cert error when trying to update the crates.io registry. For example, here's an [error building `cargo-tree`](https://github.com/NixOS/nixpkgs/runs/77715402).

```
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to sync
Caused by:
  failed to load pkg lockfile
Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`
Caused by:
  [16/-1] unexpected return value from ssl handshake -9808
```

My assumption is the sandbox is disallowing `openssl` access to the system certs. The system certs are actually stored in the Keychain but I do see certs in `/etc/ssl/` so it may be sufficient to just add `/etc/ssl/` to the `extra-sandbox-paths` on the Darwin builder.

**Comment by lilyball** [comment]
It's also possible that `/etc/ssl/` has obsolete certs in it, given that the OpenSSL that Apple ships is obsolete. I'm not sure how to test.

**Comment by LnL7** [comment]
This is an issue with the fetcher in nixpkgs, builds like that should use `cacert` instead of depending on system files that might not exist.

**Comment by LnL7** [comment]
Did some testing, but can't figure out why it's not working. SSL_CERT_FILE is already set and adding a config file with http.cainfo doesn't seem to work either.

**Comment by LnL7** [comment]
Aha it's not the certificates but `(mach-lookup com.apple.SecurityServer)`.

**Comment by lilyball** [comment]
Anything we can do to fix this?

**Comment by berbiche** [comment]
I'm currently having this exact issue when trying to build https://github.com/NixOS/nixpkgs/pull/99126 on a Darwin machine.

**Comment by starcraft66** [comment]
I'm having the same issue on darwin.

I tried connecting to https://crates.io using OpenSSL and got the following error:

```
openssl s_client -connect crates.io:443                                    ~
CONNECTED(00000005)
4676073068:error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22.260.1/libressl-2.6/ssl/ssl_pkt.c:386:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 5 bytes and written 0 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    Start Time: 1601570442
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
---
```

I suspect something is wrong with Apple's LibreSSL. Perhaps the TLS configuration changed on the crates.io server side recently that caused a bug LibreSSL to surface.

**Comment by starcraft66** [comment]
Upon further inspection, it seems the LibreSSL version shipped by apple is horribly out of date and probably has nothing to do with this issue.

**Comment by cole-h** [comment]
It looks like this should be fixed now, see e.g. https://github.com/NixOS/nixpkgs/pull/240137 ({aarch64,x86_64}-darwin built successfully).
