### ISSUE TITLE
Use less obscure arrow symbols in performance report

### ISSUE THREAD

**Issue by Synthetica9** [NixOS/ofborg#360]
![The issue, as seen on my machine](https://screenshotscdn.firefoxusercontent.com/images/61085c73-266d-491d-a00b-c8d0582a9f24.png)

Currently, [the `🡖` character (U+1F856, "South East Sans-Serif Arrow")](https://www.compart.com/en/unicode/U+1F856) is used in performance reports. This character doesn't seem to be very widely supported by fonts yet, as it was only introduced in 2014, with Unicode 7.0. 

I propose changing this to [the `↘` (U+2198, "South East Arrow")](https://www.compart.com/en/unicode/U+2198), which has much wider support, since it has been in the standard since 1993, with Unicode 1.1. 

This has the effect of rendering the character as an emoji on some platforms, which doesn't seem like a huge downside, possibly an upside.

**Comment by grahamc** [comment]
I'd love to merge a PR improving this. Mind sending one?

**Comment by Synthetica9** [comment]
@grahamc See #362
