### ISSUE TITLE
Bot that posts pre-defined comments and checklists based on files that are touched or other rules

### ISSUE THREAD

**Issue by FRidh** [NixOS/ofborg#41]
It would be nice if a bot would post pre-defined comments and/or checklists based one or more rules that are fulfilled. Types of rules could be
- file is touched
- regex matches on contents
- regex matches on commit name
- ...

The output is `markdown`.

The rules could be defined in a `yaml` or `json` file, however, if we want to match on multiple rules it may be useful to define them instead in Nix.

Example rules in some pseudo-code form:

```
if file in ["pkgs/development/python-modules/*" "pkgs/top-level/python-packages.nix" ] then post ''
- By default we enable tests. Make sure the tests are found and, in the case of libraries, are passing for all interpreters. If certain tests fail they can be disabled individually. Try to avoid disabling the tests altogether. In any case, when you disable tests, leave a comment explaining why.    
''
```

**Comment by Mic92** [comment]
Nix could be used for matching as well: https://github.com/NixOS/nix/blob/master/doc/manual/expressions/builtins.xml#L711

I would not invent a new DSL for linting. Our lowest common dominator is Nix already.

**Comment by grahamc** [comment]
@Mic92 I'd have been inclined to not use a DSL, but just do straight rust 😅 

I wonder if we need some sort of database here to match up git patch IDs (https://git-scm.com/docs/git-patch-id) to reviews to ensure comments aren't made multiple times, while still ensuring coverage while a PR changes over time.

Ideally we'd be able to make these comments in-line, so the feedback can be as close to the problem at hand as possible. Is this too ambitious?

**Comment by FRidh** [comment]
Maybe for now limit the rules to just paths, as we do with the tags in https://github.com/NixOS/ofborg/pull/59. In that case one or more paths will produce one or more comments. 

If we use a mapping, and use the paths as keys, then we may have to duplicate comments a lot. If we use a list of tuples that may be reduced. For this I think it is better to use Nix.

**Comment by FRidh** [comment]
> Ideally we'd be able to make these comments in-line, so the feedback can be as close to the problem at hand as possible. Is this too ambitious?

I would start of with just only comments based on touched files, and thus post the comments to the main thread.

**Comment by Artturin** [comment]
This likely isn't in ofborg's scope.

There's probably an action that already does this.

**Comment by Artturin** [comment]
Hmm well there is https://github.com/NixOS/ofborg/blob/released/ofborg/src/bin/github-comment-poster.rs and `githubcommentposter` but I haven't seen a comment posted by ofborg in a long time. Will let someone else decide.

**Comment by cole-h** [comment]
Yes, ofborg doesn't post comments anymore. The name is a relic, but that binary is what currently posts the GHA checkruns (`ofborg-eval`, `ofborg-eval-package-list`, etc).
