### ISSUE TITLE
OfBorg / Evaluation Performance Report never "finishes" (according to GitHub)

### ISSUE THREAD

**Issue by andir** [NixOS/ofborg#441]
The clock on the GitHub UI under "Checks" -> "OfBorg / Evaluation Performance Report" seems to be ticking forever. 

See the screenshots below:

7h 30min:
![2020-03-29-140102_793x1112_scrot](https://user-images.githubusercontent.com/638836/77848653-937b0e00-71c6-11ea-8c03-496a56f22a28.png)

44min:
![2020-03-29-135950_923x1255_scrot](https://user-images.githubusercontent.com/638836/77848655-94ac3b00-71c6-11ea-9b6c-d4305cb364af.png)

5d 2h:
![2020-03-29-140803_788x1155_scrot](https://user-images.githubusercontent.com/638836/77848681-b9a0ae00-71c6-11ea-91ed-7bad5bd62d9d.png)

At first I thought that might just be "normal" and it only shows you when it started. Looking at another job convinced me of the opposite. It should actually tell you when it finished:
![2020-03-29-141041_712x342_scrot](https://user-images.githubusercontent.com/638836/77848726-316ed880-71c7-11ea-9ce9-581a43021aa4.png)

We are perhaps just missing the final call to GitHub that tells them that the eval step is done?

**Comment by Artturin** [comment]
I haven't seen this happen.

I'm guessing the reason this could happen is that GitHub dropped the call.
