### ISSUE TITLE
RabbitMQ Stability

### ISSUE THREAD

**Issue by grahamc** [NixOS/ofborg#45]
I really don't like to restart RabbitMQ because not all clients properly handle the disconnect. However, it must be done, especially under NixOS where it restarts practically every time the channel updates.

- [x] write a nix-darwin service for a builder, ensuring it has some restart logic
- [x] convert graham's mac to use nix-darwin
- [x] configure RabbitMQ to listen on ipv6 since the DNS record already has an AAAA.
- [x] ensure the core services don't restart too fast and will continue trying to start for several minutes
- [x] ensure the rust workers properly detect a lost connection
- [x] implement better heartbeats
- [x] in the PHP code receiving events from GitHub, it should repeatedly attempt to connect to RabbitMQ and send the event, for up to 30 seconds, to better handle events sent during a transient problem

In the future we may want multiple rabbitmq nodes, but clustering can be annoying, so I'm punting on that for now.

**Comment by grahamc** [comment]
A quick experiment of breaking the network connection revealed some good news and some bad news. The builder / evaluator correctly realize the connection is broken within a couple minutes and quits. RabbitMQ however doesn't seem to touch the connection ever again: the client hasn't asked for a new message, so it isn't has no reason to talk to it. If the worker had any jobs in progress, those jobs are never then put back to the Ready state on the server to be attempted again. This is typically solved by heartbeats, but the amqp library we're using doesn't support heartbeats at this time. This is why I implemented the "plastic" heartbeat, to ensure there is regular traffic over the connection. However, because the plastic heartbeats are client-driven, the server doesn't have any idea the client is misbehaving.

The amqp lib not supporting proper heartbeats is a problem worth looking at, though, so I'll see what I can do.

**Comment by grahamc** [comment]
In https://github.com/grahamc/rust-amqp/commit/be492890a30884be391b2effc0a6dfb3d02f74f6 I added somewhat okay support for real heartbeats on channel 0. It isn't 100% according to spec, but should get the job done. In  https://github.com/NixOS/ofborg/commit/9e829b4a2e8ff1c5e37443d7f299938af45bec45 (currently on next) I delete the "plastic" heartbeat support instead relying on the core heartbeat support.

**Comment by grahamc** [comment]
PHP is now retrying connections on the web end via ba92804ea5a9c67f586776ae96f6d18af04ff94b

**Comment by LnL7** [comment]
Added a basic service definition in https://github.com/LnL7/nix-darwin/commit/5fa6f21d06ef939d287aeec4ac318031e7e187e1.
Let me know if you run into any issues. Ideally this would also SIGHUP when the config changes, is that supported or is a normal restart safe?

**Comment by grahamc** [comment]
Right now ofborg can't reload configs, so a full restart would have to be done.

**Comment by grahamc** [comment]
This seems to be done, a rabbitmq restart was completed and all the workers running before the restart joined up again promptly.

**Comment by LnL7** [comment]
What happens when a build is running, does it get requeued?
