### ISSUE TITLE
Review comment should link directly to attempt log

### ISSUE THREAD

**Issue by jtojnar** [NixOS/ofborg#49]
Currently the full log link in the review comment links to the main (`-ofborg-`) tab. This is not very helpful when there are many logs and you want to view a particular failure.

**Comment by grahamc** [comment]
This feature is done and deployed. Builders will take some time to update, and so some builder's links will not link directly to a log. Once all builders update, all log links will be to the exact attempt.

**Comment by grahamc** [comment]
Example of where it has worked: https://github.com/NixOS/nixpkgs/pull/34481#issuecomment-362126696
