### ISSUE TITLE
Provide a list of attribute names that will must be rebuilt

### ISSUE THREAD

**Issue by andir** [NixOS/ofborg#54]
When providing a PR `ofborg` currently tags a PR with the approximate amount of rebuilds this PR will trigger. In addition to the amount of attributes it would be nice if the list of attributes would be exposed.

**Comment by FRidh** [comment]
I would also like to have this. And for each derivation also its maintainers. Of course, in that case it should not include a `@` when including the list in a comment.

**Comment by Ericson2314** [comment]
https://github.com/Gabriel439/nix-diff integration with this would make it eve more awesome @gabriel439, though it's also of course something that can be easily run by hand with a more basic dump.

**Comment by grahamc** [comment]
https://gist.github.com/GrahamcOfBorg/610fb22842908db9720d53d4f6741f9f
