### ISSUE TITLE
Status of x86_64-darwin builds? Disable those builds/checks?

### ISSUE THREAD

**Issue by primeos** [NixOS/ofborg#557]
For a long time I've noticed that CI will add checks for `$pkg, $pkg.passthru.tests on x86_64-darwin` if the PR is created by a trusted user but I've only seen them in the "Queued — Waiting to run this check..." status and never actually succeeding or failing.

The annoying thing is that the CI status will be stuck at "Some checks haven’t completed yet" and the status icon will remain the yellow circle. Here's an example of such a check that is queued for almost 150 days now: https://github.com/NixOS/nixpkgs/pull/105273 https://github.com/NixOS/nixpkgs/pull/105273/checks?check_run_id=1467992622.

Would it be possible that we either disable the x86_64-darwin builds entirely or that we add a queuing timeout for them?

I hope there isn't already an issue for this. From a quick search I've only found #529 which raises the question if there even are some Darwin builders available (from the currently observable behaviour it looks like there are none).

**Comment by jonringer** [comment]
Agreed, I was just about to make an issue as well. It's been almost half a year. At best the check no longer provides value, at worse it's detrimental to the review process.

cc @grahamc

**Comment by grahamc** [comment]
I totally agree with both of you, I'm sorry the check was there, misleading, for so long. We have a darwin builder configured now.

**Comment by grahamc** [comment]
(Note I've been working on this all week, maybe some of last week too. So ... good timing :) )

**Comment by vcunat** [comment]
Thanks, having it really helps with some PRs.
