### ISSUE TITLE
Disable trusted users by default

### ISSUE THREAD

**Issue by cole-h** [NixOS/ofborg#559]
The current Darwin build machine is restarted and erased relatively frequently, so the sandboxing isn't as much of a worry anymore

- [x] Add `"enable_trusted_users": true/false,` toggle to `config.public.json`
- [x] Skip ACL stuff if that is `false`
- [x] Update README
- [x] Close all trusted user PRs

We don't want to remove the ACL stuff, just in case... It's easy to toggle back on if anything unexpected happens.

**Comment by grahamc** [comment]
> restarted

-> restarted and erased
