### ISSUE TITLE
aarch64-darwin

### ISSUE THREAD

**Issue by domenkozar** [NixOS/ofborg#569]
It would be great to have aarch64-darwin support.

Just getting the evaluation going would be valuable for PRs like https://github.com/NixOS/nixpkgs/pull/128581

**Comment by vcunat** [comment]
Maybe re-assign one of the six Hydra workers.  I think it's become the least loaded platform on Hydra.

**Comment by domenkozar** [comment]
It's not only a problem of having the builders but even for evaluation there need to be code changes to ofborg (if I understand correctly).

**Comment by vcunat** [comment]
Ah, right, the evaluation checks shouldn't need an aarch64-darwin machine, and those checks are what seems to be missing the most.

**Comment by r-burns** [comment]
Getting rebuild-amount labels would be really helpful too for PRs like https://github.com/NixOS/nixpkgs/pull/142684

**Comment by domenkozar** [comment]
Done in master
