### ISSUE TITLE
Usage Change Log

### ISSUE THREAD

**Issue by grahamc** [NixOS/ofborg#6]
I want a way to easily ping people when things about using the bot change, so here we are...

cc people with access:

@7c6f434c
@adisbladis
@copumpkin
@disassembler
@domenkozar
@fpletz
@fridh
@globin
@grahamc
@jtojnar
@lheckemann
@lnl7
@mic92
@nequissimus
@orivej
@shlevy
@srhb
@zimbatm

**Comment by grahamc** [comment]
You can now ask the bot to run tests on PRs: https://github.com/grahamc/ofborg#test-added-2017-11-24

**Comment by grahamc** [comment]
Added @vcunat and @aszlib to the ACL.

**Comment by grahamc** [comment]
Added @vcunat and @aszlig to the ACL.

**Comment by grahamc** [comment]
The bot used to clone per PR, which wasted a lot of space. I've changed this to use a single build dir. This should speed up builds a bit (though not a ton -- it was using a local cache for clones) but we may find edge cases where it doesn't properly clean up between builds. Let me know if you see anything weird.

**Comment by Mic92** [comment]
@grahamc have you tried using `git-worktree`? I use this in my [review](https://github.com/Mic92/dotfiles/blob/master/nixos/mypackages/nix-review/review.py#L83) script concurrently without any problem

**Comment by vcunat** [comment]
Beware if the script is (still) using `git clone --shared` for rebuild-amount estimate, as that's breaking with worktrees for me. (I haven't tried to check upstream why this happens.)

**Comment by grahamc** [comment]
Please open other issues to discuss stuff, and keep this dedicated to change announcements.

**Comment by grahamc** [comment]
Evaluation checks no longer contain stdout`s data, making errors easier to find. Additionally, the Details link will only be provided if there is an evaluation error.

**Comment by grahamc** [comment]
@garbas can now call ofborg

**Comment by grahamc** [comment]
@rbvermaa can now call ofborg

**Comment by grahamc** [comment]
@peti can now call ofborg

**Comment by grahamc** [comment]
cc @yegortimoshenko, @veprbl

**Comment by grahamc** [comment]
cc @aneeshusa

**Comment by grahamc** [comment]
cc @jb55, @joachifm, @andir

**Comment by grahamc** [comment]
Too many people have access now for this thread to work.
