### ISSUE TITLE
`@ofborg test installer` did not run installer tests, yet succeeded

### ISSUE THREAD

**Issue by roberth** [NixOS/ofborg#608]
See https://github.com/NixOS/nixpkgs/pull/177672#event-6867843030

**Comment by ncfavier** [comment]
Duplicate of https://github.com/NixOS/ofborg/issues/504, the workaround is `@ofborg build nixosTests.installer`.

**Comment by cole-h** [comment]
Since https://github.com/NixOS/ofborg/pull/630, we've switched to using `nixosTests` rather than the `nixos/release.nix`'s `tests` :)
