### ISSUE TITLE
OfBorg doesn't fail upon encountering an evaluation error for a newly added package

### ISSUE THREAD

**Issue by winterqt** [NixOS/ofborg#610]
[Here](https://github.com/NixOS/nixpkgs/pull/186309#event-7183682578), OfBorg marked the PR as having 0 rebuilds because the package [contained `stdenvnoCC` instead of `stdenvNoCC`](https://github.com/NixOS/nixpkgs/commit/e3550ccf0d389f1513db5f259db2401585e53b28#diff-9a38bbffb1bd6b325d48fd7faaa7a50b29a9ee412e60a6f108027ca1dfdac9bcR8), but didn't provide any other indication that it failed to eval. Ideally, it would be a bit more vocal -- though I'm not sure why the package list eval didn't catch this.

**Comment by Artturin** [comment]
was fixed in https://github.com/NixOS/nixpkgs/commit/d9f767600fb2f5f0b7e7159cd8638c0701ad6bfc
