### ISSUE TITLE
Tags: support `8.has: package (new)`

### ISSUE THREAD

**Issue by FRidh** [NixOS/ofborg#63]
The `8.has: package (new)` tag is perhaps one of the most uninteresting tags we have because packages are added continuously. At the same time, for statistical purposes this tag may be interesting. 

We could assign this tag based on whether a PR has a net increase in amount of packages as listed by `nix-env -qaP`. This makes the assumption that we count a new version of a package also as a new package. I don't mind that, actually.

At the same time, when there is a net decrease in amount of packages, we may also add the `8.has: clean-up` tag.

**Comment by 7c6f434c** [comment]
Maybe has:new-package should be only auto-applied when there is a new package and no package disappears? Otherwise many changes to the details of wrapping would be a coin-toss between clean-up and new-package, while not being either…

**Comment by FRidh** [comment]
> Maybe has:new-package should be only auto-applied when there is a new package and no package disappears?

It's a better indicator but more difficult to implement.

> Otherwise many changes to the details of wrapping would be a coin-toss between clean-up and new-package, while not being either…

What kind of wrapping?

There are situations where both `new` and `removal` would apply but only one of them would be chosen and which one would indeed be a coin-toss.

**Comment by 7c6f434c** [comment]
>> Maybe has:new-package should be only auto-applied when there is a new package and no package disappears?
>It's a better indicator but more difficult to implement.

Aren't you pushing the list of packages into a set at some point? Then you can check std::hash_set::Difference in both directions and check if either of the differences is empty.

>> Otherwise many changes to the details of wrapping would be a coin-toss between clean-up and new-package, while not being either…
>What kind of wrapping?

Ah, we don't have any Firefox-wrapped-with-different plugins derivations now. I picked a bad example. Maybe ImageMagick situation with a few overrides that differ only in setting some inputs to `null` is a better case.

**Comment by grahamc** [comment]
Good thinking with the hash_set::difference :)

**Comment by grahamc** [comment]
https://github.com/NixOS/nixpkgs/pull/34798#event-1467849876

**Comment by FRidh** [comment]
Nice work, thanks!
