### ISSUE TITLE
error: a 'x86_64-linux' … is required … but I am a 'aarch64-darwin'

### ISSUE THREAD

**Issue by avdv** [NixOS/ofborg#677]
For this PR https://github.com/NixOS/nixpkgs/pull/283480, this [check](https://logs.ofborg.org/?key=nixos/nixpkgs.283480&attempt_id=fa5b7721-0842-4196-94b5-f1b71d336761) is failing with:
```
error: a 'x86_64-linux' with features {} is required to build '/nix/store/lg08mm0jgnwfp5dvc3raid7q2hxw0y7a-boot.json.drv', but I am a 'aarch64-darwin' with features {benchmark, big-parallel, nixos-test}
```
Note, this is on x86_64-darwin.

**Comment by 0x4A6F** [comment]
See https://github.com/NixOS/nixpkgs/issues/294725

**Comment by roberth** [comment]
This is an infrastructure problem. The machines that run ofborg should be configured to have remove builders.

A similar problem is experienced by `nixosTests.docker-tools-cross`, which needs remote builds to test a simple cross compiled docker image. (The kind of cross compilation that's _almost completely_ cached on `cache.nixos.org` except for the docker image itself, so running this _is_ feasible.).

**Comment by avdv** [comment]
OK, I didn't even realize this was about linux vs. darwin... :see_no_evil: 

Closing.
