### ISSUE TITLE
Ping meta.maintainers

### ISSUE THREAD

**Issue by FRidh** [NixOS/ofborg#70]
We still need to ping maintainers of packages/modules in case their expressions are modified.

Proposal:

1. use `nix-env` to check which packages need to be rebuild
2. retrieve for each package `meta.position` 
3. check if the file specified in 2) is in the diff. If so, ping the maintainers listed in `somepkg.meta.maintainers`.

The attributes are typically GitHub handles, but as far as I know there is no way in Nix to get that handle.

Two possible solutions to retrieve the handle:
1. rewrite `lib.maintainers` (https://github.com/NixOS/nixpkgs/issues/18352#issuecomment-244905440)
2. use sed

**Comment by FRidh** [comment]
Maintainers change in Nixpkgs: https://github.com/NixOS/nixpkgs/pull/34842

**Comment by 7c6f434c** [comment]
I think there is also an option to have a separate table (in Nix or in CSV) of email-as-listed → github handle, full name, IRC nick…

**Comment by FRidh** [comment]
Note the Nixpkgs change is in (https://github.com/NixOS/nixpkgs/pull/36119)

**Comment by Profpatsch** [comment]
I would love if someone implemented this for ofborg. https://github.com/ryantm/nix-update already [uses the new github handles](https://github.com/ryantm/nix-update/commit/0954b0b8591fd206640b5a0abf116399fd335551).

**Comment by grahamc** [comment]
Step #3 seems particularly complicated... I wonder if @vcunat has had an opportunity to come up with a "root change" script?

**Comment by FRidh** [comment]
@grahamc what is complicated about step 3? `meta.position` includes a filename. Or do you mean "it would be nice if there was a simpler solution"?

**Comment by vcunat** [comment]
No, not yet.

**Comment by 7c6f434c** [comment]
Maybe label PRs about packages that miss maintainers, too? Got the idea after reading the discussion: https://github.com/NixOS/nixpkgs/issues/54249

**Comment by dasJ** [comment]
Is this still relevant? Ofborg already pings maintainers if they are in the org

**Comment by grahamc** [comment]
Thanks!
