### ISSUE TITLE
Automatically tag issues with data from nix-info

### ISSUE THREAD

**Issue by davidak** [NixOS/ofborg#8]
### Example

 - system: `"x86_64-darwin"`
 - host os: `Darwin 14.5.0, macOS 10.10.5`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.13`
 - channels(davidak): `"nixpkgs-18.03pre121255.45a85eaceb"`
 - channels(root): `"nixpkgs-18.03pre121255.45a85eaceb"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

So we get the information that the user has the issue with this system. That does **not** mean that it appears only on this kind of system. Often other users mention in the comments that they also have the same problem on a different system. But then, additional tags can be added manually.

We could extract:

- `6.topic: darwin`
- OS version like `17.09` on NixOS (?)
- Nix version (?)
- maybe we can enhance `nix-info` to output if the channel is `stable`, `small` or `unstable`?

Since i'm not involved in tagging, let's ask people that are.

cc @joachifm @vcunat @NeQuissimus @FRidh

**Comment by cole-h** [comment]
There's no easy way to trigger CI on issues, sadly.
