### ISSUE TITLE
Distinguish tests from evals and other checks more closely

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/ofborg#80]
When I run the `test` command, currently I get a comment response like:

```
Failure on aarch64-linux (full log)

Partial log (click to expand)
```

which is the same like a normal build response, and I can see whether it was for the test or the build only by looking at the log.
This is especially confusing when giving multiple commands, like I did in in https://github.com/NixOS/nixpkgs/pull/35194#issuecomment-366799784

I propose changing the comment text to contain a reference to what was built/evaluated/tested, like

```
Test for `rabbitmq` failed on `aarch64-linux` (full log)

Partial log:
```

**Comment by Mic92** [comment]
```
Build for `rabbitmq` failed on `aarch64-linux` (full log)
```

**Comment by Artturin** [comment]
ofborg no longer comments
