### ISSUE TITLE
Spurious failures on unsupported systems

### ISSUE THREAD

**Issue by shlevy** [NixOS/ofborg#90]
If I touch a package that is known not to build on darwin, I get an error like https://github.com/NixOS/nixpkgs/pull/35666#issuecomment-368476092

**Comment by 7c6f434c** [comment]
Timeouts could also benefit from being reported separately. Unlike platform checks, timeout failures can sometimes require fetching the whole log (if more than ten packages depend on the long-build one)

**Comment by 7c6f434c** [comment]
I am not sure how feasible it is to recognise out-of-space failures separately…
