### ISSUE TITLE
Remove merge conflict tag (perhaps add it too?)

### ISSUE THREAD

**Issue by edef1c** [NixOS/ofborg#96]
Sometimes humans add the tag, and it doesn't get cleared up by them after a rebase. Having the bot handle it would keep it in sync better.

**Comment by Mic92** [comment]
conflicts with https://github.com/NixOS/ofborg/issues/94 slightly

**Comment by grahamc** [comment]
Closed in 5820df9683545d0fca2ee5428ceb6d8af71859a4 thanks!
